version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080
      - REACT_APP_VULNERABLE_URL=http://vulnerable:5001
    depends_on:
      - backend
      - vulnerable

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/websec?allowPublicKeyRetrieval=true&useSSL=FALSE
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=websec
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  vulnerable:
    build: ./Vulnerable
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production