version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080
      - REACT_APP_VULNERABLE_URL=http://vulnerable:5001
    depends_on:
      - backend
      - vulnerable

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  vulnerable:
    build: ./Vulnerable
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production